"""empty message

Revision ID: 153e6cffd36a
Revises: 42a4fae49395
Create Date: 2021-07-02 22:17:47.938078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153e6cffd36a'
down_revision = '42a4fae49395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
