"""empty message

Revision ID: 40dc1de28dc3
Revises: 06b54fb6b04b
Create Date: 2021-07-12 14:02:09.286224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dc1de28dc3'
down_revision = '06b54fb6b04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('image_profile', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=20), nullable=False),
    sa.Column('image_category', sa.String(length=30), nullable=True),
    sa.Column('type_category_id', sa.Integer(), nullable=True),
    sa.Column('url_for_category', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['type_category_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('url_for_category')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('link', sa.String(length=220), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('image_tool', sa.String(length=20), nullable=False),
    sa.Column('image_preview', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('type_tool', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('location', sa.VARCHAR(length=64), nullable=True),
    sa.Column('about_me', sa.TEXT(), nullable=True),
    sa.Column('avatar_hash', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_tool')
    op.drop_table('tool')
    op.drop_table('category')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('type')
    # ### end Alembic commands ###
