"""empty message

Revision ID: 469256147b32
Revises: 1fc0628d565c
Create Date: 2021-07-03 13:03:48.008699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469256147b32'
down_revision = '1fc0628d565c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
