"""empty message

Revision ID: 473e614e9149
Revises: 25573710f732
Create Date: 2021-07-02 21:32:29.326599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473e614e9149'
down_revision = '25573710f732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
