"""empty message

Revision ID: 5c13e224e7a2
Revises: 8ba4bd3bf6f1
Create Date: 2021-07-03 14:46:55.376510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c13e224e7a2'
down_revision = '8ba4bd3bf6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###
