"""empty message

Revision ID: 873b846c8f4c
Revises: c9a78382ce27
Create Date: 2021-07-03 12:59:42.417714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873b846c8f4c'
down_revision = 'c9a78382ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
