"""empty message

Revision ID: 8ba4bd3bf6f1
Revises: 469256147b32
Create Date: 2021-07-03 13:18:42.044447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba4bd3bf6f1'
down_revision = '469256147b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', app.models.MyDateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', app.models.MyDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
