"""empty message

Revision ID: 94628be4a035
Revises: 5c13e224e7a2
Create Date: 2021-07-05 16:07:22.287730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94628be4a035'
down_revision = '5c13e224e7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
