"""empty message

Revision ID: da20280410b8
Revises: a38444a70d16
Create Date: 2021-07-02 20:24:47.896592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da20280410b8'
down_revision = 'a38444a70d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
